config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="main-content" style="background-color: white;">
  <div class="container">
    <div class="row">
      <h1>All properties (<%= @flats.count %>)</h1>
    </div>
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-4" style="width: 24rem;">
          <div class="card">
            <div class="card-img">
              <img class="card-img-top" src="<%= flat.img_url %>" alt="Flat image" style="height: 200px;">
            </div>
            <div class="card-body">
              <h4 class="card-title"><%= flat.name %></h4>
              <p class="card-text"><%= flat.address %></p>
              <div class="row">
                <h5 style="margin-right: 18px;"><i class="fas fa-users"></i><%= flat.number_of_guests %></h5>
                <h5><i class="fas fa-pound-sign"></i><%= flat.price_per_night %></h5>
              </div>
            </div>
            <div class="card-footer">
              <%= link_to 'More info', root_path%>
              <%= link_to 'Edit', root_path%>
              <%= link_to 'Remove', root_path%>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="main-content" style="background-color: white;">
  <div class="container">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="add-new-form">
          <h1>Add a new flat</h1>
          <%= simple_form_for @flat do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <%= f.input :img_url %>
          <%= f.submit class: "btn btn-outline-success" %>
          <%= link_to 'Cancel', root_path, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-expand-lg navbar-light bg-light">
    <h3>Simple AirBnB</h3>
    <div class="collapse navbar-collapse">
      <div class="ml-auto flex">
        <%= link_to 'Add a Flat', new_flat_path, class: "btn btn-outline-dark"%>
      </div>
    </div>
  </header>
    <%= yield %>
  </body>
</html>